### ISSUE TITLE
Metapackages report checksum mismatches when README changes

### ISSUE THREAD

**Issue by timotheecour** [maxim-belkin/homebrew-xorg#254]
it fails (after i ran `brew upgrade`); it even fails with a fresh brew repo
 
```
brew install linuxbrew/xorg/libxtst
==> Installing libxtst from linuxbrew/xorg
==> Installing dependencies for linuxbrew/xorg/libxtst: xorg-protocols, libxau, libxdmcp, libxcb, gpatch, libx11, libxfixes, libxext, libxi
==> Installing linuxbrew/xorg/libxtst dependency: xorg-protocols
==> Downloading https://raw.githubusercontent.com/Linuxbrew/homebrew-xorg/master/README.md
Already downloaded: /home/timothee/.cache/Homebrew/xorg-protocols-latest.md
Error: SHA256 mismatch
Expected: 76b4fd623d6b10d816069aedcffc411e2c9abc607533adf3fa810d7904b5f9d1
Actual: 7d5cca1b4bdc2a3aefe2ef7fedf919ea8fe4f907493d5d31661c5f8fa81a3161
Archive: /home/timothee/.cache/Homebrew/xorg-protocols-latest.md
To retry an incomplete download, remove the file above.
```

furthermore:
brew gist-logs linuxbrew/xorg/libxtst
Error: No logs.

**Comment by bw-yuhogg** [comment]
Can you try deleting /home/timothee/.cache/Homebrew/xorg-protocols-latest.md and then retrying the installation? Thanks!

**Comment by timotheecour** [comment]
thanks, works, but isn't that fragile?

**Comment by timotheecour** [comment]
@sjackman could you add a label category `workaround_available` that would mean there's a workaround even though the bug is not 100% fixed, so the bug becomes low priority? (this particular one could be closed i guess but `workaround_available` is still useful in general IMO

**Comment by bw-yuhogg** [comment]
> thanks, works, but isn't that fragile?

Yeah, it is. It's been bugging me for a while; thanks for reminding me.

Here's the situation: four of the formulae (xorg, xorg-apps, xorg-fonts, and xorg-protocols) are metapackages whose only purpose is to depend on the smaller individual formulae. This means they lack a canonical URL, so for two of them we just use the README for this repo as a placeholder.

Whenever we update the README, we therefore also have to update the `sha256` and `version` lines in those two formulae. Unfortunately, while I remembered to update the `sha256` I forgot about the `version`.

Since you already had an old copy of the README cached, and the version numbers were the same even though the contents were different, `brew` reported a SHA-256 mismatch.

I think a better fix for this would be for me to create a gist with contents like "PLEASE DO NOT EDIT THIS FILE. IT NEEDS TO BE KEPT THE SAME FOREVER FOR FORMULAE IN HOMEBREW-XORG." and use that instead of the README as the download URL. That means we would never again have to bump the version number for those formulae and this problem won't come up again.

**Comment by timotheecour** [comment]
why not use instead a versioned file instead? eg:

eg something like: https://github.com/ldc-developers/ldc/blob/v1.1.0-beta6/README.md
or https://github.com/ldc-developers/ldc/blob/a95f90f5172fa0c82cd4f6ff48ebb34464c90ea5/README.md

instead of https://github.com/ldc-developers/ldc/blob/master/README.md ?

**Comment by bw-yuhogg** [comment]
> why not use instead a versioned file instead? eg:

I decided to do so. Thanks for the suggestion!
