### ISSUE TITLE
MESA: "Error: Operation already in progress for mesa.formula"

### ISSUE THREAD

**Issue by sandrasi** [maxim-belkin/homebrew-xorg#451]
- [x] Ran `brew update` and retried your prior step?
```bash
$ brew update
Already up-to-date.
```
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
```bash
$ brew doctor
Your system is ready to brew.
```
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug report
When I try to install the `mesa` package I get the following error:
```
$ brew install mesa
Error: Operation already in progress for mesa.formula
Another active Homebrew process is already using mesa.formula.
Please wait for it to finish or terminate it to continue.
```
There isn't any other Homebrew process running. A similar issue has been reported on [Stack Overflow](https://stackoverflow.com/questions/39797078/another-active-homebrew-process-is-already-in-progress) but the recommended solution (deleting the lock files) does not work: after emptying the `/home/linuxbrew/.linuxbrew/var/homebrew/locks/` directory, the installation fails with the same error message. Is there perhaps a circular dependency between the `mesa` package and its dependencies that is not handled correctly?

It might be unrelated but I did find a [comment](https://github.com/Linuxbrew/homebrew-xorg/blob/master/Formula/mesa.rb#L42-L47) in the `mesa` formula that describes a circular dependency between the `mesa` and the `libva` packages, but if that is really the reason of the installation failure, I have no idea how to fix it because the directions are uncertain and inconsistent:
- the comment in the `mesa` package says that the `libva` package should be installed first _with the `disable-egl` and `disable-egl` options_ (same option mentioned twice!), whereas
- the [comment](https://github.com/Linuxbrew/homebrew-xorg/blob/master/Formula/libva.rb#L15-L20) in the `libva` package says that the package should be installed before `mesa` _with the `disable-glx` option_.

So which one is it? Also, these notes suggest that one has to use a command line installation option but neither of the `disable-egl` and `disable-glx` options is a valid option. I have therefore edited the `libva` formula and installed the package using `$ brew install libva --build-from-source` but the `mesa` package still can't be installed.

**Comment by jwhite007** [comment]
@sandrasi, I'm having this exact same problem.

**Comment by maxim-belkin** [comment]
Let me first address the lock issue: most likely this has something to do with the filesystem you're on. We've seen reports in the past that were caused by the NFS file system. You can try setting `HOMEBREW_TEMP` to, let say, `/dav/shm` (if you have enough RAM) and see if it helps. But be sure to delete those lock files before trying it (I'm not sure if `brew doctor` reports locks...)

Next, see if you can try this solution:  https://github.com/Homebrew/brew/issues/253#issuecomment-248801969

There is no circular dependency in mesa/libva formulae. I added those comments when I was working on the formulae. Initially, they were in sync and I guess that I forgot to update one of them when updating the formulae.

I'll keep this issue open. Please continue to post questions or report any progress.

**Comment by jwhite007** [comment]
I did ```export HOMEBREW_TEMP="/dev/shm"```. That did not solve the problem. I then set it back to the original path and emptied that directory. That didn't work either. I then looked at the solution to which @maxim-belkin links above. This is not a permissions issue, however. This is a fresh set-up of Linuxbrew, and I've been installing other applications without a hitch. I'm still at a loss as to why this is happening.

**Comment by maxim-belkin** [comment]
Can you try specifying `linuxbrew/xorg/mesa` instead of just `mesa`? I suspect there is a problem with name collision or something: `homebrew/core` added `mesa` formula a few months ago...

**Comment by jwhite007** [comment]
@maxim-belkin, good call, sir. The problem was definitely due to a collision. ```brew install linuxbrew/xorg/mesa``` does the trick!!!

```
$ find . -name mesa.rb
./Library/Taps/homebrew/homebrew-core/Formula/mesa.rb
./Library/Taps/linuxbrew/homebrew-xorg/Formula/mesa.rb
```

**Comment by maxim-belkin** [comment]
Yeah... this is the downside of being a downstream: upstream does not ~care~ know about formulae that already exist in downstream repositories. With the Linuxbrew/Homebrew merger that recently happened that shouldn't happen in the future, but... 

There is still a problem with linuxbrew/xorg/mesa formula: `llvm@4` no longer has a bottle, so we either have to use a different compiler (in which case we wouldn't be able to use some of llvm's benefits) or make llvm ~great again~ compile again

**Comment by maxim-belkin** [comment]
Mesa formula was updated in #484

**Comment by YuMan-Tam** [comment]
This problem seems to persist in the latest version of the formula. I believe the root cause is the same as suggested by https://github.com/Linuxbrew/homebrew-xorg/issues/451#issuecomment-467978343. 

The formula depends on ```freeglut```, which in turn depends on ```linuxbrew/xorg/xorg```. When I did ```brew install mesa``` in a clean ```brew``` installation, ```brew``` automatically downloads the ```linuxbrew/xorg``` tap every time and try to instead install ```linuxbrew/xorg/mesa```.

When I comment out the ```freeglut``` dependency, the problem went away. So I believe it's an issue of name conflict.
